services:
  outline-postgres:
    image: postgres:${OUTLINE_POSTGRES_VERSION}
    container_name: outline-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OUTLINE_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${OUTLINE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OUTLINE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${OUTLINE_POSTGRES_DB}
    volumes:
      - ./vol/outline-postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - outline-private

  outline-redis:
    image: redis:${OUTLINE_REDIS_VERSION}
    container_name: outline-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./outline-redis/usr/local/etc/redis/:/usr/local/etc/redis/
      - ./vol/outline-redis/data/:/data/
    networks:
      - outline-private

  outline-app:
    image: outlinewiki/outline:${OUTLINE_APP_VERSION}
    container_name: outline-app
    restart: unless-stopped
    depends_on:
      - outline-postgres
      - outline-redis
    environment:
      URL: ${OUTLINE_APP_URL}
      COLLABORATION_URL: ${OUTLINE_APP_URL}
      SECRET_KEY: ${OUTLINE_APP_SECRET_KEY}
      UTILS_SECRET: ${OUTLINE_APP_UTILS_SECRET}
      FORCE_HTTPS: ${OUTLINE_FORCE_HTTPS}
      NODE_ENV: ${OUTLINE_NODE_ENV}
      DATABASE_URL: postgres://${OUTLINE_POSTGRES_USER}:${OUTLINE_POSTGRES_PASSWORD}@outline-postgres:5432/${OUTLINE_POSTGRES_DB}
      PGSSLMODE: disable
      REDIS_URL: redis://outline-redis:6379
      SMTP_HOST: ${OUTLINE_SMTP_HOST}
      SMTP_PORT: ${OUTLINE_SMTP_PORT}
      SMTP_USERNAME: ${OUTLINE_SMTP_USER}
      SMTP_PASSWORD: ${OUTLINE_SMTP_PASS}
      SMTP_FROM_EMAIL: ${OUTLINE_SMTP_FROM}
      SMTP_SECURE: ${OUTLINE_SMTP_SECURE}
      OIDC_CLIENT_ID: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_SECRET}
      OIDC_AUTH_URI: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_SERVER_URL/realms/$OUTLINE_KEYCLOAK_REALM/protocol/openid-connect/auth}
      OIDC_TOKEN_URI: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_SERVER_URL/realms/$OUTLINE_KEYCLOAK_REALM/protocol/openid-connect/token}
      OIDC_USERINFO_URI: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_SERVER_URL/realms/$OUTLINE_KEYCLOAK_REALM/protocol/openid-connect/userinfo}
      OIDC_LOGOUT_URI: ${OUTLINE_KEYCLOAK_OAUTH:+$OUTLINE_KEYCLOAK_SERVER_URL/realms/$OUTLINE_KEYCLOAK_REALM/protocol/openid-connect/logout}
      OIDC_SCOPES: ${OUTLINE_KEYCLOAK_OAUTH:+openid profile email}
      OIDC_DISPLAY_NAME: ${OUTLINE_KEYCLOAK_OAUTH:+OpenID}
      OIDC_USERNAME_CLAIM: ${OUTLINE_KEYCLOAK_OAUTH:+preferred_username}
      OIDC_LOGOUT_ENABLED: ${OUTLINE_KEYCLOAK_OAUTH:+true}
      #OIDC_GROUPS_CLAIM: groups
      #OIDC_GROUPS_ALLOWED: outline-access
      OIDC_EMAIL_DOMAIN: ${OUTLINE_KEYCLOAK_OAUTH:+""}      
    volumes:
      - ./vol/outline-app/var/lib/outline/:/var/lib/outline/
    networks:
      - proxy-client-outline
      - outline-private

networks:
  proxy-client-outline:
    name: proxy-client-outline
    external: true
    
  outline-private:
    name: outline-private
    driver: bridge
    internal: true